version: 2.1

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build

# jobs:
#   build:
#     working_directory: ~/mern-starter
#     docker:
#       - image: circleci/node:10.16.3
#       - image: mongo:4.2.0
#     steps:
#       - checkout
#       - run:
#           name: update-npm
#           command: 'sudo npm install -g npm@5'
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#       - run:
#           name: install-npm-wee
#           command: npm install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: test
#           command: npm test
#       - run:
#           name: code-coverage
#           command: './node_modules/.bin/nyc report --reporter=text-lcov'
#       - store_artifacts:
#           path: test-results.xml
#           prefix: tests
#       - store_artifacts:
#           path: coverage
#           prefix: coverage
#       - store_test_results:
#           path: test-results.xml

# version: 2.1


commands:
  print_pipeline_id:
    description: "Testing how to use command to reduce duplications in pipeline script"
    parameters:
      to:
        type: string
        default: "Salaudeen O. Abdulrasaq"
    steps:
      - run: 
          command: |
            echo ${CIRCLE_WORKFLOW_ID}
            echo "Hello" <<parameters.to>>
            
            
jobs: 
  save_hello_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          command: |
            echo "hello world of " ${MY_FULL_NAME}  > ~/output.txt
            
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
            
      


  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
          to: "Allison Okikiola Omowunmi"


  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          command: |
            cat ~/output.txt
         
            
        
  
workflows:
  my_workflow:
    jobs:
      - my_job:
          requires:
            - save_hello_world
            - print_output_file
        
      - save_hello_world
      - print_output_file:
          requires:
            - save_hello_world
     
